import { Header } from '@/widgets/header'
import type { Metadata } from 'next'
import { Geist, Geist_Mono, Open_Sans, Roboto_Serif } from 'next/font/google'
import { PropsWithChildren } from 'react'
import './assets/globals.css'
import Providers from './providers'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin']
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin']
})

const robotoSans = Roboto_Serif({
	variable: '--font-roboto-serif',
	subsets: ['latin']
})

const openSans = Open_Sans({
	variable: '--font-open-sans',
	subsets: ['latin']
})

export const metadata: Metadata = {
	title: 'Donation',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html
			lang='en'
			className={`${geistSans.variable} ${geistMono.variable} ${robotoSans.variable} ${openSans.variable} h-full antialiased`}
		>
			<body>
				<Providers>
					<Header />
					<main>{children}</main>
				</Providers>
			</body>
		</html>
	)
}
